# Generated by Django 5.0.6 on 2024-06-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=60, verbose_name='First name')),
                ('last_name', models.CharField(max_length=60, verbose_name='Last name')),
                ('picture_url', models.URLField(blank=True, null=True, verbose_name='Photo URL')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email address')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(verbose_name='IS ACTIVE')),
                ('is_admin', models.BooleanField(verbose_name='IS ADMIN')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
