# Generated by Django 5.0.6 on 2024-06-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='IS ACTIVE'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='IS ADMIN'),
        ),
    ]
