# Generated by Django 5.0.6 on 2024-06-12 06:35

import apps.user.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_useraccount_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='useraccount',
            managers=[
                ('objects', apps.user.models.UserAccountManager()),
            ],
        ),
    ]
