# Generated by Django 5.0.6 on 2024-06-07 07:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedHomework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PEND', 'Pending'), ('RESOLV', 'Resolved'), ('NORES', 'No resolved')], default='PEND', max_length=6)),
                ('grade', models.PositiveSmallIntegerField()),
                ('solution', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, size=None)),
            ],
        ),
    ]
