# Generated by Django 5.0.6 on 2024-06-07 07:48

import apps.classroom.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_url', models.URLField(blank=True, null=True)),
                ('picture_url', models.URLField(blank=True, null=True)),
                ('accept_invitation', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Name')),
                ('access_code', models.CharField(max_length=7, unique=True, validators=[apps.classroom.validators.validate_access_code])),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('section', models.CharField(blank=True, max_length=50, null=True, verbose_name='Section')),
                ('subject', models.CharField(blank=True, max_length=30, null=True, verbose_name='Subject')),
                ('room', models.CharField(blank=True, max_length=30, null=True, verbose_name='Room')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Name')),
                ('hex', models.CharField(max_length=7, unique=True, validators=[apps.classroom.validators.validate_hex_color])),
            ],
        ),
    ]
