# Generated by Django 5.0.6 on 2024-06-15 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_alter_classroom_access_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='accept_invitation',
            new_name='available_join',
        ),
    ]
