# Generated by Django 5.0.6 on 2024-06-17 00:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_rename_class_room_homework_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='resources',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, size=None),
        ),
    ]
