# Generated by Django 5.0.6 on 2024-06-15 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='class_room',
            new_name='classroom',
        ),
    ]
